version: "3"
services:
  foundryvtt:
    container_name: foundryvtt
    image: node:14.15.5-alpine3.13
    ports:
      - "80:30000"
    restart: always
    command: ["node", "/foundryvtt/resources/app/main.js", "--headless"]
    volumes:
      - ./foundryvtt:/foundryvtt
      - ./foundrydata:/root/.local/share/FoundryVTT

  tinyfilemanager:
    container_name: tinyfilemanager
    image: shoyuvanilla/tinyfilemanager-forfvtt
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./:/app/tinyfilemanager/data
      - ./tinyfilemanager-config.php:/app/tinyfilemanager/config.php

  wiki:
    container_name: wiki
    image: linuxserver/dokuwiki
    ports:
      - "8000:8000"
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Seoul
    volumes:
      - ./wiki:/config
