version: "3"
services:
  https-portal:
    environment:
      DOMAINS: "foo.mydomain.com -> http://foundryvtt:30000, bar.mydomain.com -> http://tinyfilemanager:80, baz.mydomain.com -> http://wiki:80"
